<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdbcba06f0469bcc1ade11ec8564123eb
{
    public static $classMap = array (
        'InstagramAPI\\Comment' => __DIR__ . '/..' . '/mgp25/instagram-php/src/http/Response/Comment.php',
        'InstagramAPI\\ConfigureResponse' => __DIR__ . '/..' . '/mgp25/instagram-php/src/http/Response/ConfigureResponse.php',
        'InstagramAPI\\ConfigureVideoResponse' => __DIR__ . '/..' . '/mgp25/instagram-php/src/http/Response/ConfigureVideoResponse.php',
        'InstagramAPI\\Constants' => __DIR__ . '/..' . '/mgp25/instagram-php/src/Constants.php',
        'InstagramAPI\\HttpInterface' => __DIR__ . '/..' . '/mgp25/instagram-php/src/http/HttpInterface.php',
        'InstagramAPI\\Instagram' => __DIR__ . '/..' . '/mgp25/instagram-php/src/Instagram.php',
        'InstagramAPI\\InstagramException' => __DIR__ . '/..' . '/mgp25/instagram-php/src/InstagramException.php',
        'InstagramAPI\\InstagramRegistration' => __DIR__ . '/..' . '/mgp25/instagram-php/src/InstagramRegistration.php',
        'InstagramAPI\\LoginResponse' => __DIR__ . '/..' . '/mgp25/instagram-php/src/http/Response/LoginResponse.php',
        'InstagramAPI\\MediaInfoResponse' => __DIR__ . '/..' . '/mgp25/instagram-php/src/http/Response/MediaInfoResponse.php',
        'InstagramAPI\\Response' => __DIR__ . '/..' . '/mgp25/instagram-php/src/http/Response/Response.php',
        'InstagramAPI\\Settings' => __DIR__ . '/..' . '/mgp25/instagram-php/src/Utils/Settings.php',
        'InstagramAPI\\SignatureUtils' => __DIR__ . '/..' . '/mgp25/instagram-php/src/SignatureUtils.php',
        'InstagramAPI\\UploadJobVideoResponse' => __DIR__ . '/..' . '/mgp25/instagram-php/src/http/Response/UploadJobVideoResponse.php',
        'InstagramAPI\\UploadPhotoResponse' => __DIR__ . '/..' . '/mgp25/instagram-php/src/http/Response/UploadPhotoResponse.php',
        'InstagramAPI\\UploadVideoResponse' => __DIR__ . '/..' . '/mgp25/instagram-php/src/http/Response/UploadVideoResponse.php',
        'InstagramAPI\\User' => __DIR__ . '/..' . '/mgp25/instagram-php/src/http/Response/User.php',
        'InstagramAPI\\UserAgent' => __DIR__ . '/..' . '/mgp25/instagram-php/src/http/UserAgent.php',
        'InstagramAPI\\Utils' => __DIR__ . '/..' . '/mgp25/instagram-php/src/Utils/Utils.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInitdbcba06f0469bcc1ade11ec8564123eb::$classMap;

        }, null, ClassLoader::class);
    }
}
