<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
 
return array(
    'InstagramAPI\\Comment' => $vendorDir . '/mgp25/instagram-php/src/http/Response/Comment.php',
    'InstagramAPI\\ConfigureResponse' => $vendorDir . '/mgp25/instagram-php/src/http/Response/ConfigureResponse.php',
    'InstagramAPI\\ConfigureVideoResponse' => $vendorDir . '/mgp25/instagram-php/src/http/Response/ConfigureVideoResponse.php',
    'InstagramAPI\\Constants' => $vendorDir . '/mgp25/instagram-php/src/Constants.php',
    'InstagramAPI\\HttpInterface' => $vendorDir . '/mgp25/instagram-php/src/http/HttpInterface.php',
    'InstagramAPI\\Instagram' => $vendorDir . '/mgp25/instagram-php/src/Instagram.php',
    'InstagramAPI\\InstagramException' => $vendorDir . '/mgp25/instagram-php/src/InstagramException.php',
    'InstagramAPI\\InstagramRegistration' => $vendorDir . '/mgp25/instagram-php/src/InstagramRegistration.php',
    'InstagramAPI\\LoginResponse' => $vendorDir . '/mgp25/instagram-php/src/http/Response/LoginResponse.php',
    'InstagramAPI\\MediaInfoResponse' => $vendorDir . '/mgp25/instagram-php/src/http/Response/MediaInfoResponse.php',
    'InstagramAPI\\Response' => $vendorDir . '/mgp25/instagram-php/src/http/Response/Response.php',
    'InstagramAPI\\Settings' => $vendorDir . '/mgp25/instagram-php/src/Utils/Settings.php',
    'InstagramAPI\\SignatureUtils' => $vendorDir . '/mgp25/instagram-php/src/SignatureUtils.php',
    'InstagramAPI\\UploadJobVideoResponse' => $vendorDir . '/mgp25/instagram-php/src/http/Response/UploadJobVideoResponse.php',
    'InstagramAPI\\UploadPhotoResponse' => $vendorDir . '/mgp25/instagram-php/src/http/Response/UploadPhotoResponse.php',
    'InstagramAPI\\UploadVideoResponse' => $vendorDir . '/mgp25/instagram-php/src/http/Response/UploadVideoResponse.php',
    'InstagramAPI\\User' => $vendorDir . '/mgp25/instagram-php/src/http/Response/User.php',
    'InstagramAPI\\UserAgent' => $vendorDir . '/mgp25/instagram-php/src/http/UserAgent.php',
    'InstagramAPI\\Utils' => $vendorDir . '/mgp25/instagram-php/src/Utils/Utils.php',
);
